# Generated by Django 6.0.2 on 2026-02-06 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('de', 'Deutsch')], default='ru', max_length=2)),
                ('tone', models.CharField(choices=[('strict', 'Строгий'), ('friendly', 'Дружелюбный')], default='friendly', max_length=10)),
                ('depth', models.CharField(choices=[('short', 'Кратко'), ('detailed', 'Подробно')], default='detailed', max_length=10)),
                ('format', models.CharField(choices=[('bullets', 'Список'), ('paragraphs', 'Параграфы')], default='bullets', max_length=10)),
                ('goal', models.CharField(choices=[('exam', 'Экзамен'), ('homework', 'Домашнее задание'), ('understand', 'Понимание')], default='understand', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('explanation', 'Объяснение'), ('summary', 'Конспект'), ('plan', 'План'), ('quiz', 'Тест')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='prompts.prompt')),
            ],
            options={
                'unique_together': {('prompt', 'type', 'version')},
            },
        ),
    ]
