# Generated by Django 6.0.2 on 2026-06-04 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['user', '-created_at'], name='prompts_pro_user_id_6fdc10_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['session_key', '-created_at'], name='prompts_pro_session_213a42_idx'),
        ),
    ]
