# Generated by Django 6.0.2 on 2026-02-06 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('de', 'Deutsch')], default='ru', max_length=2)),
                ('tone', models.CharField(choices=[('strict', 'Строгий'), ('friendly', 'Дружелюбный')], default='friendly', max_length=10)),
                ('depth', models.CharField(choices=[('short', 'Кратко'), ('detailed', 'Подробно')], default='detailed', max_length=10)),
                ('format', models.CharField(choices=[('bullets', 'Список'), ('paragraphs', 'Параграфы')], default='bullets', max_length=10)),
                ('goal', models.CharField(choices=[('exam', 'Экзамен'), ('homework', 'Домашнее задание'), ('understand', 'Понимание')], default='understand', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
