# Generated by Django 6.0.2 on 2026-02-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='action_type',
            field=models.CharField(choices=[('prompt', 'New Prompt'), ('regenerate', 'Regeneration')], default='prompt', max_length=20),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='prompts.prompt'),
        ),
    ]
